# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='haveFunUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女')], default=1)),
                ('age', models.PositiveIntegerField(default=18)),
                ('address', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('img', models.TextField(blank=True, null=True)),
                ('user_type', models.IntegerField(choices=[(0, '超级用户'), (1, '普通用户')], default=1)),
                ('passwd', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='userHeadImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='head_images')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_test.haveFunUser')),
            ],
        ),
    ]
